  
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MCC
      uses: actions/checkout@v1
      with:
        path: MC-Combat
    - name: Checkout Movecraft
      uses: actions/checkout@v2
      with:
        repository: 'APDevTeam/Movecraft'
        path: Movecraft
    - run: ls
    - run: pwd
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Build Movecraft
    - run:  mvn -B package --file Movecraft/pom.xml

    # Build MCC
    - run: mvn -B package --file MC-Combat/pom.xml

    - name: Stage jar
      run: mkdir staging && cp target/Movecraft-Combat*.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Combat*.jar staging/Movecraft-Combat_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: MCC_Dev-Build
        path: staging/Movecraft-Combat_*.jar
