  
name: Java CI

on: [push, pull_request]

jobs:
  # Build 1.14.4 NMS
  pillage_1_14_4:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache 1.14.4 Maven package
        id: cachePillage
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.14.4
          restore-keys: ${{ runner.os }}-1.14.4
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.14.4
          restore-keys: ${{ runner.os }}-m2_1.14.4

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.14.4
        id: pillage
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/craftbukkit-1.14.4-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.14.4
        if: steps.pillage.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.14.4 --compile craftbukkit

  # Build 1.15.2 NMS
  bees_1_15_2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache 1.15.2 Maven package
        id: cacheBees
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.15.2-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.15.2
          restore-keys: ${{ runner.os }}-1.15.2
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.15.2
          restore-keys: ${{ runner.os }}-m2_1.15.2

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.15.2
        id: bees
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.15.2-R0.1-SNAPSHOT/craftbukkit-1.15.2-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.15.2
        if: steps.bees.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.15.2 --compile craftbukkit

  # Build 1.16.1 NMS
  nether_1_16_1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache 1.16.1 Maven package
        id: cacheNether
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.1-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.16.1
          restore-keys: ${{ runner.os }}-1.16.1
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.16.1
          restore-keys: ${{ runner.os }}-m2_1.16.1

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.16.1
        id: nether
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.16.1-R0.1-SNAPSHOT/craftbukkit-1.16.1-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.16.1
        if: steps.nether.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.16.1 --compile craftbukkit

  # Build 1.16.3 NMS
  nether_1_16_3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache 1.16.3 Maven package
        id: cacheNether
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.3-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.16.3
          restore-keys: ${{ runner.os }}-1.16.3
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.16.3
          restore-keys: ${{ runner.os }}-m2_1.16.3

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.16.3
        id: nether2
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.16.3-R0.1-SNAPSHOT/craftbukkit-1.16.3-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.16.3
        if: steps.nether2.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.16.3 --compile craftbukkit

  # Build 1.16.5 NMS
  nether_1_16_5:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache 1.16.5 Maven package
        id: cacheNether
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/
          key: ${{ runner.os }}-1.16.5
          restore-keys: ${{ runner.os }}-1.16.5
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.16.5
          restore-keys: ${{ runner.os }}-m2_1.16.5

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.16.5
        id: nether3
        run: test -f ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/craftbukkit-1.16.5-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.16.5
        if: steps.nether3.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.16.5 --compile craftbukkit

  build:
    runs-on: ubuntu-latest
    needs: [pillage_1_14_4, bees_1_15_2, nether_1_16_1, nether_1_16_3, nether_1_16_5]

    steps:
    - name: Checkout Movecraft-Combat
      uses: actions/checkout@v2
      with:
        path: Movecraft-Combat
    - name: Checkout Movecraft
      uses: actions/checkout@v2
      with:
        repository: 'APDevTeam/Movecraft'
        path: Movecraft
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Cache 1.14.4 Maven package
      id: cachePillage
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.14.4-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-1.14.4
        restore-keys: ${{ runner.os }}-1.14.4
    - name: Cache 1.15.2 Maven package
      id: cacheBees
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.15.2-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-1.15.2
        restore-keys: ${{ runner.os }}-1.15.2
    - name: Cache 1.16.1 Maven package
      id: cacheNether1
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.1-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-1.16.1
        restore-keys: ${{ runner.os }}-1.16.1
    - name: Cache 1.16.3 Maven package
      id: cacheNether2
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.3-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-1.16.3
        restore-keys: ${{ runner.os }}-1.16.3
    - name: Cache 1.16.5 Maven package
      id: cacheNether3
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/bukkit/craftbukkit/1.16.5-R0.1-SNAPSHOT/
        key: ${{ runner.os }}-1.16.5
        restore-keys: ${{ runner.os }}-1.16.5
    
    # Build Movecraft
    - name: Build Movecraft
      run:  mvn -B package -T 1C --file Movecraft/pom.xml

    # Build Movecraft-Combat
    - name: Build Movecraft-Combat
      run: mvn -B package -T 1C --file Movecraft-Combat/pom.xml

    - name: Stage jar
      run: mkdir staging && cp Movecraft-Combat/target/Movecraft-Combat*.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Combat*.jar staging/Movecraft-Combat_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Movecraft-Combat_Dev-Build
        path: staging/Movecraft-Combat_*.jar
