  
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MCC
      uses: actions/checkout@v2
      with:
        path: MC-Combat
    - name: Checkout Movecraft
      uses: actions/checkout@v2
      with:
        repository: 'APDevTeam/Movecraft'
        path: Movecraft
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Run Spigot BuildTools for NMS if required
    - name: Setup BuildTools
      if: steps.cache.outputs.cache-hit != 'true'
      run: mkdir BuildTools
    - name: Download BuildTools
      if: steps.cache.outputs.cache-hit != 'true'
      run: wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: 1.10.2
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.10.2
    - name: 1.11.2
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.11.2
    - name: 1.12.2
      if: steps.cache.outputs.cache-hit != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.12.2
    
    # Build Movecraft
    - name: Build Movecraft
      run:  mvn -B package -T 1C --file Movecraft/pom.xml

    # Build MCC
    - name: Build Movecraft-Combat
      run: mvn -B package -T 1C --file MC-Combat/pom.xml

    - name: Stage jar
      run: mkdir staging && cp MC-Combat/target/Movecraft-Combat*.jar staging
    - name: Rename jar
      run: mv staging/Movecraft-Combat*.jar staging/Movecraft-Combat_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: MCC_Dev-Build
        path: staging/Movecraft-Combat_*.jar
