name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [created, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Movecraft-Combat
      uses: actions/checkout@v3
      with:
        path: Movecraft-Combat
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    # Build Movecraft-Combat
    - name: Build Movecraft-Combat
      run: mvn -B package -T 1C --file Movecraft-Combat/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
